Algoritmo "semnome"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Antonio Carlos Nicolodi 
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 11/08/2020
Var
// Seção de Declarações das variáveis 
p1, p2, p3, p4, p5, p6, p7, p8, p9, p10, p11, p12, p13, p14, p15 : caracter
m1, m2, m3, m4, m5, m6, m7, m8, m9, m10, m11, m12, m13, m14, m15 : inteiro
c1, c2, c3, c4, c5, c6, c7, c8, c9, c10, c11, c12, c13, c14, c15 : inteiro

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
p1 <- "EUA"
 m1 <- 166295
  c1 <- 5254561
p2 <- "Brasil"
 m2 <- 101857
  c2 <- 3057470
p3 <- "India"
 m3 <- 45550
  c3 <- 2287511
p4 <- "Russia"
 m4 <- 15131
  c4 <- 897599
p5 <- "AfricaSul"
 m5 <- 10621
  c5 <- 563598
p6 <- "México"
 m6 <- 53003
  c6 <- 485836
p7 <- "Peru"
 m7 <- 21276
  c7 <- 483133
p8 <- "Colombia"
 m8 <- 13154
  c8 <- 397623
p9 <- "Chile"
 m9 <- 10139
  c9 <- 375044
p10 <- "Espanha"
 m10 <- 28576
  c10 <- 370060
p11 <- "Ira"
 m11 <- 18800
  c11 <- 331189
p12 <- "Reino Unido"
 m12 <- 46526
  c12 <- 311641
p13 <- "Arabia Saudita"
 m13 <- 3233
  c13 <- 291468
p14 <- "Paquistão"
 m14 <- 6112
  c14 <- 285191
p15 <- "Bangladesh"
 m15 <- 3471
  c15 <- 263503

escreval ("           CASOS E MORTES DE COVID-19 PELO MUNDO       ")
escreval()
escreval ("PAIS                      CASOS               MORTES   ")
escreval ("1 - ", p1, "                  ", c1, "               ", m1)
escreval ("2 - ", p2, "               ", c2, "               ", m2)
escreval ("3 - ", p3, "                ", c3, "               ", m3)
escreval ("4 - ", p4, "               ", c4, "                ", m4)
escreval ("5 - ", p5, "            ", c5, "                ", m5)
escreval ("6 - ", p6, "               ", c6, "                ", m6)
escreval ("7 - ", p7, "                 ", c7, "                ", m7)
escreval ("8 - ", p8, "             ", c8, "                ", m8)
escreval ("9 - ", p9, "                ", c9, "                ", m9)
escreval ("10 - ", p10, "             ", c10, "                ", m10)
escreval ("11 - ", p11, "                 ", c11, "                ", m11)
escreval ("12 - ", p12, "         ", c12, "                ", m12)
escreval ("13 - ", p13, "      ", c13, "                ", m13)
escreval ("14 - ", p14, "           ", c14, "                ", m14)
escreval ("15 - ", p15, "          ", c15, "                ", m15)

escreval()
escreval ("media casos: ", (c1 + c2 + c3 + c4 + c5 + c6 + c7 + c8 + c9 + c10 + c11 + c12 + c13 + c14 + c15)/15)
escreval()
escreval ("media mortes: ", (m1 + m2 + m3 + m4 + m5 + m6 + m7 + m8 + m9 + m10 + m11 + m12 + m13 + m14 + m15)/15)




Fimalgoritmo