Algoritmo "semnome"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Antonio Carlos Nicolodi 
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 10/08/2020
Var
// Seção de Declarações das variáveis 
num1 : inteiro

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
para num1 de 1 ate 1000 faca
     escreval ("PROA 4.0")
fimpara

Fimalgoritmo