Algoritmo "semnome"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Antonio Carlos Nicolodi 
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 06/08/2020
Var
// Seção de Declarações das variáveis 
comida,nome : caracter

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 

nome <- "lucas"
comida <- "rabanete"

Fimalgoritmo