Algoritmo "semnome"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Antonio Carlos Nicolodi 
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 13/08/2020
Var
resultado, valor : inteiro


Inicio


enquanto resultado <= 1000 faca
 resultado <- resultado + 7
escreva (resultado)
 escreval()
fimenquanto


Fimalgoritmo