Algoritmo "semnome"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Antonio Carlos Nicolodi 
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 10/08/2020
Var
// Seção de Declarações das variáveis 
contador : inteiro
 // commando enquanto e fimenquanto

Inicio
contador <- 100

enquanto contador >1 faca
escreval (contador, " - mery pfff!!")
   contador <- contador - 2
 fimenquanto


Fimalgoritmo