Algoritmo "semnome"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Antonio Carlos Nicolodi 
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 13/08/2020
Var
num : inteiro

Inicio
escreva ("digite o numero: ")
 leia (num)
escreval()
 escreval ("numero: ", num)
escreval()
 escreval("antecessor: ", num - 1)
escreval()
 escreval ("sucessor: ", num + 1)




Fimalgoritmo