Algoritmo "semnome"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Antonio Carlos Nicolodi 
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 19/08/2020
Var
numeros: vetor[1..5] de inteiro
aux, posicao, posteste : inteiro



Inicio
para posicao de 1 ate 5 faca
 escreva("digite o numero: ")
  leia(numeros[posicao])
fimpara

para posicao de posteste+1 de 1 ate 4 faca



Fimalgoritmo